# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pub" # Ecosystem of Dart packages
    directory: "/" # Location of package manifests
    assignees:
      - "alexanderserraris"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "alexanderserraris"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

    # Enable version updates for Gradle
  - package-ecosystem: "gradle" # TODO: check if dependabot opens PRs for gradle
    directory: "/android"
    assignees:
      - "alexanderserraris"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
