targets:
  $default:
    builders:
      graphql_codegen:
        options:
          generatedFileHeader: "// ignore_for_file: type=lint\n"
          clients:
            - graphql
            - graphql_flutter
          scalars:
            DateTime:
              type: DateTime