targets:
  $default:
    builders:
      graphql_codegen:
        options:
          generatedFileHeader: "// ignore_for_file: type=lint\n"
          scalars:
            DateTime:
              type: DateTime
