name: ksrvnjord_main_app
description: K.S.R.V. Njord Ledenapplicatie
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.4+16

environment:
  sdk: "^3.5.0" # Dart SDK version, TODO: update when codemagic updated: https://dart.dev/get-dart/archive
  flutter: ^3.24.0 # Flutter SDK version: https://docs.flutter.dev/release/archive

# Want to remove unused dependencies from your package?
# Find the unused dependencies by running the following in the root of your package
# $ flutter pub run dependency_validator
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  url_launcher: ^6.1.5
  styled_widget: ^0.4.0+3
  get_it: ^8.0.0
  intl: ^0.19.0
  flutter_markdown: ^0.7.3+2
  flutter_secure_storage: ^9.0.0
  dio: ">=4.0.6 <6.0.0"
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  syncfusion_flutter_calendar: ^27.1.51
  lucide_icons: ^0.257.0
  sticky_headers: ^0.3.0+2
  firebase_auth: ^4.20.0
  time_range_picker: ^2.2.0
  firebase_core: any
  shared_preferences: ^2.0.15
  firebase_messaging: any
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  cloud_functions: ^4.4.1
  firebase_storage: any
  multi_select_flutter: ^4.1.3
  font_awesome_flutter: ^10.4.0
  action_sheet: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.2
  firebase_app_check: ^0.2.0
  tuple: ^2.0.1
  path_provider: ^2.0.2
  flutter_riverpod: ^2.5.1
  timeago: ^3.3.0
  expandable_text: ^2.3.0
  easy_image_viewer: ^1.2.0
  yaml: ^3.1.1
  flutter_svg: ^2.0.0
  share_plus: ^10.0.0
  expandable: ^5.0.1
  weather_icons: ^3.0.0
  csv: any
  stack_trace: ^1.11.0
  firebase_analytics: any
  firebase_crashlytics: any
  upgrader: any
  sliver_tools: ^0.2.12
  flutter_pdfview: ^1.3.1
  go_router: ^14.2.9
  package_info_plus: ^4.1.0
  flutter_web_plugins:
    sdk: flutter
  firebase_pagination: # Forked to add capability to refresh widget on Firebase Query change.
    git:
      url: https://github.com/ksrvnjord/firebase_pagination

  json_annotation: ^4.9.0
  universal_html: ^2.2.4
  image_picker: ^1.0.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: any
  autologin: ^1.0.0

  collection: any
dependency_overrides:
  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  dependency_validator: ^4.1.1
  json_serializable: ^6.7.1
  custom_lint: any
  riverpod_generator: any
  riverpod_lint: any
  freezed: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/sponsors/
    - assets/data/
    - assets/images/sponsors/
