name: ksrvnjord_main_app
description: K.S.R.V. Njord Ledenapplicatie

version: 0.0.24+13

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  provider: ^6.0.3
  url_launcher: ^6.1.5
  sentry_flutter: ^6.9.1
  graphql: ^5.1.3
  graphql_flutter: ^5.1.1
  gql: ^0.14.0
  styled_widget: ^0.4.0+3
  google_fonts: ^3.0.1
  oauth2: ^2.0.0
  get_it: ^7.2.0
  intl: ^0.17.0
  routemaster: ^1.0.1
  flutter_markdown: ^0.6.10+5
  page_transition: ^2.0.9
  flutter_secure_storage: ^6.0.0
  dio: ^4.0.6
  shimmer: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  flutter_staggered_grid_view: ^0.6.2
  syncfusion_flutter_calendar: ^20.2.48
  webview_flutter: ^3.0.4
  lucide_icons: ^0.102.0
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_sliders: ^20.3.52
  firebase_auth: ^4.1.3
  permission_handler: ^10.2.0
  time_range_picker: ^2.2.0
  firebase_core: ^2.3.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  file_picker: ^5.2.4
  image_picker_widget: '>=2.0.0 <3.0.0'
  firebase_storage: ^11.0.9
  fluttertoast: ^8.1.2
  cached_network_image: ^3.2.3
  localstorage: ^4.0.0+1
  cloud_functions: ^4.0.7
  multi_select_flutter: ^4.1.3
  flutter_pdfview: ^1.2.5
  font_awesome_flutter: ^10.4.0
  feedback: ^2.5.0
  feedback_sentry: ^2.3.0
  action_sheet: ^1.0.4
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  graphql_codegen: ^0.12.0-beta.1
  build_runner: ^2.2.0
  dart_code_metrics: ^5.5.1

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/
   - assets/documents/

