name: ksrvnjord_main_app
description: K.S.R.V. Njord Ledenapplicatie
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1726.2+13

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.7.7

# Want to remove unused dependencies from your package?
# Find the unused dependencies by running the following in the root of your package
# $ flutter pub run dependency_validator
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  url_launcher: ^6.1.5
  sentry_flutter: ^7.5.2
  graphql: ^5.1.3
  graphql_flutter: ^5.1.1
  gql: ^0.14.0
  styled_widget: ^0.4.0+3
  google_fonts: ^4.0.4
  oauth2: ^2.0.0
  get_it: ^7.2.0
  intl: ^0.17.0
  routemaster: ^1.0.1
  flutter_markdown: ^0.6.10+5
  flutter_secure_storage: ^8.0.0
  dio: ">=4.0.6 <6.0.0"
  shimmer: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  syncfusion_flutter_calendar: ^21.2.3
  lucide_icons: ^0.216.0
  sticky_headers: ^0.3.0+2
  firebase_auth: '>=3.0.0'
  time_range_picker: ^2.2.0
  firebase_core: ^2.11.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^14.0.0+1
  flutter_localizations:
    sdk: flutter
  image_picker_widget: '>=2.0.0 <3.0.0'
  firebase_storage: ^11.0.9
  cloud_functions: ^4.0.7
  multi_select_flutter: ^4.1.3
  flutter_pdfview: ^1.2.5
  font_awesome_flutter: ^10.4.0
  feedback_sentry: ^2.4.0
  action_sheet: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.2
  firebase_app_check: ^0.1.2
  tuple: ^2.0.1
  path_provider: ^2.0.2
  flutter_riverpod: ^2.2.0
  riverpod_generator: ^1.1.1
  timeago: ^3.3.0
  expandable_text: ^2.3.0
  easy_image_viewer: ^1.2.0
  yaml: ^3.1.1
  flutter_svg: ^2.0.5
  expandable: ^5.0.1
  weather_icons: ^3.0.0
  stack_trace: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  graphql_codegen: ^0.12.0-beta.1
  build_runner: ^2.2.0
  dart_code_metrics: ^5.5.1
  hive_generator: ^2.0.0
  dependency_validator: ^3.2.2

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/
   - assets/documents/
   - assets/data/

