name: ksrvnjord_main_app
description: K.S.R.V. Njord Ledenapplicatie

publish_to: 'none'
version: 0.0.4+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  url_launcher: ^6.1.5
  sentry_flutter: ^6.9.1
  graphql: ^5.1.1
  graphql_flutter: ^5.1.1-beta.4
  gql: ^0.13.2-alpha+1659715356091
  styled_widget: ^0.4.0+3
  google_fonts: ^3.0.1
  oauth2: ^2.0.0
  get_it: ^7.2.0
  intl: ^0.17.0
  routemaster: ^1.0.1
  flutter_markdown: ^0.6.10+5
  page_transition: ^2.0.9
  flutter_secure_storage: ^6.0.0
  dio: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  graphql_codegen: ^0.11.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/

