name: ksrvnjord_main_app
description: K.S.R.V. Njord Ledenapplicatie
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1726.10+13

environment:
  sdk: "^2.19.4" # Dart SDK version: https://dart.dev/get-dart/archive
  flutter: ^3.10.0 # Flutter SDK version: https://docs.flutter.dev/release/archive

# Want to remove unused dependencies from your package?
# Find the unused dependencies by running the following in the root of your package
# $ flutter pub run dependency_validator
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  url_launcher: ^6.1.5
  sentry_flutter: ^7.10.1
  graphql: ^5.1.3
  graphql_flutter: ^5.1.1
  gql: ^0.14.0
  styled_widget: ^0.4.0+3
  oauth2: ^2.0.0
  get_it: ^7.2.0
  intl: ^0.18.0
  routemaster: ^1.0.1
  flutter_markdown: ^0.6.10+5
  flutter_secure_storage: ^8.0.0
  dio: ">=4.0.6 <6.0.0"
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  syncfusion_flutter_calendar: ^23.1.36
  lucide_icons: ^0.244.0
  sticky_headers: ^0.3.0+2
  firebase_auth: ">=3.0.0"
  time_range_picker: ^2.2.0
  firebase_core: ^2.11.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.2
  flutter_localizations:
    sdk: flutter
  image_picker_widget: ">=2.0.0 <3.0.0"
  cloud_functions: ^4.4.1
  firebase_storage: ^11.2.7
  multi_select_flutter: ^4.1.3
  font_awesome_flutter: ^10.4.0
  feedback_sentry: ^2.4.0
  action_sheet: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.2
  firebase_app_check: ^0.2.0
  tuple: ^2.0.1
  path_provider: ^2.0.2
  flutter_riverpod: ^2.2.0
  riverpod_generator: ^2.2.3
  timeago: ^3.3.0
  expandable_text: ^2.3.0
  easy_image_viewer: ^1.2.0
  yaml: ^3.1.1
  flutter_svg: any
  share_plus: any
  expandable: ^5.0.1
  weather_icons: ^3.0.0
  stack_trace: ^1.11.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.1
  upgrader: any
  sliver_tools: ^0.2.12
  flutter_pdfview: ^1.3.1
  go_router: ^11.1.2

dependency_overrides:
  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  graphql_codegen: ^0.12.0-beta.1
  build_runner: ^2.4.6
  dart_code_metrics: # Dart Code Metrics became PAID-only, that's why we use our own forked version.
    git: # Visit https://dart-code-metrics.web.app/ for the docs.
      url: https://github.com/ksrvnjord/dart-code-metrics.git
  hive_generator: ^2.0.0
  dependency_validator: ^3.2.2
  dart_code_metrics_presets: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/data/
