# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean assembleRelease")
  end

  desc "Submit a new Beta Build to Google Play beta track"
  lane :beta do
    version_codes = google_play_track_version_codes(
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      track: 'internal'
    )

    new_vc = version_codes.max.to_i + 1
    android_set_version_code(
      version_code: new_vc
    )
    gradle(task: "clean bundleRelease")

    upload_to_play_store(
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      skip_upload_metadata: true,
      track: 'internal'
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to Google Play"
  lane :deploy do
    version_codes = google_play_track_version_codes(
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      track: 'production'
    )

    new_vc = version_codes.max.to_i + 1
    android_set_version_code(
      version_code: new_vc
    )
    gradle(task: "clean bundleRelease")

    upload_to_play_store(
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      track: 'production'
    )
  end
end
