# This is a basic workflow to help you get started with Actions

name: CI Android App Bundle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual running of this action
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build the Android App Bundle with Flutter
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
            distribution: 'zulu'
            java-version: '11'
    - uses: subosito/flutter-action@v2
    - name: Get dependencies
      run: flutter pub get
#     - name: Run tests
#       run: flutter test
    - name: Build App Bundle
      run: flutter build appbundle
      
    - name: Upload App Bundle Artifact
      uses: actions/upload-artifact@v2
      with:
        name: njord_android_bundle
        path: $GITHUB_WORKSPACE/build/app/outputs/bundle/release/app-release.aab
        if-no-files-found: error
  sign:
    runs-on: ubuntu-latest
    name: Sign the App Bundle
    needs: build
    steps:
      - name: Download App Bundle Artifact
        uses: actions/download-artifact@v2
        with:
          name: njord_android_bundle
      - name: Sign AAB
        id: signer
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: $HOME
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Signed AAB Artifact
        uses: actions/upload-artifact@v2
        with:
          name: njord_android_bundle_signed
          path: ${{steps.signer.outputs.signedReleaseFile}}
    
