# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart Code Metrics

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  check:
    name: dart-code-metrics-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Flutter action
        # You may pin to the exact commit or the version.
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check unused files
        run: flutter pub run dart_code_metrics:metrics check-unused-files --exclude=/**.graphql.dart lib
      
      - name: Check unnecessary nullable parameters
        run: flutter pub run dart_code_metrics:metrics check-unnecessary-nullable lib

      - name: dart-code-metrics
        # uses: dart-code-checker/dart-code-metrics-action@v3 # commented because this action isn't updated to latest flutter with intl 0.18.0
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   fatal_warnings: true
        #   fatal_performance: true
        #   fatal_style: false # We can turn this fatal when we have fixed most issues
        run: flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings --reporter=console






