# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart Code Metrics

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  flutter_version: "3.7.7"

jobs:
  check-files-and-nullable-params:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check unused files
        run: flutter pub run dart_code_metrics:metrics check-unused-files --exclude=/**.graphql.dart lib
      
      - name: Check unnecessary nullable parameters
        run: flutter pub run dart_code_metrics:metrics check-unnecessary-nullable lib
  
  dartcodemetrics-analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
    
      - name: Install dependencies
        run: flutter pub get
      
      - name: dart-code-metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings --reporter=console







