# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Analyze

on:
  pull_request:
    branches: [ "main" ]
  push: 
    branches: [ "main" ]
jobs:
  check:
    name: flutter-analyze-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        # You may pin to the exact commit or the version.
        uses: subosito/flutter-action@v2.8.0
        
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze
