name: Dart Formatting 
on:
  pull_request:
    branches:
      - "main"
      - "!dependabot/**" # Ignore automatic PRs from dependabot
    paths:
      - "lib/**"
jobs:
  formatting:
    name: Dart Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4 # Checkout the code in the main repo
      - name: Install Stable Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"
      - name: Format files
        run: dart format --set-exit-if-changed .
