name: Dart Formatting
on:
  pull_request:
    branches:
      - "main"
      - "!dependabot/**" # Ignore automatic PRs from dependabot
    paths:
      - "lib/**"
jobs:
  formatting:
    name: Dart Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4 # Checkout the code in the main repo
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.x
          cache: true
      - name: Dependencies # Required to prepare dart format
        run: flutter pub get
      - name: Format files
        run: dart format --set-exit-if-changed .
