# This run all static analysis tools and checks for unused files and unnecessary nullable parameters
# Caches Flutter dependencies to speed up the process

name: Static Analysis

on:
  pull_request:
    branches:
      - "main"
      - "!dependabot/**" # Ignore automatic PRs from dependabot
    paths:
      - "lib/**"

env:
  flutter_version: "3.24.3"
  dcm_version: "1.22.0"

jobs:
  analyze:
    name: Flutter analyze / Dart Code Metrics Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Flutter action
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze --fatal-warnings --fatal-infos .

  other:
    name: Dart Format / Validate dependencies / Check unnecessary nullable parameters
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4 # Checkout the code in the main repo

      - name: Install Stable Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Format files
        run: dart format --set-exit-if-changed .
