# This run all static analysis tools and checks for unused files and unnecessary nullable parameters
# Caches Flutter dependencies to speed up the process

name: Static Analysis

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  flutter_version: "3.7.7"

jobs:
  check-unused-files:
    name: Check unused files
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check unused files
        run: flutter pub run dart_code_metrics:metrics check-unused-files --exclude=/**.graphql.dart lib

  check-nullable-params:
    name: Check unnecessary nullable parameters
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Check unnecessary nullable parameters
        run: flutter pub run dart_code_metrics:metrics check-unnecessary-nullable lib
  
  dartcodemetrics-analyze:
    name: Dart code metrics analyze
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
    
      - name: Install dependencies
        run: flutter pub get
      
      - name: dart-code-metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings --reporter=console

  flutter-analyze:
    name: Flutter analyze
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
    
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze code
        run: flutter analyze --fatal-warnings --fatal-infos .

  dart-format:
    name: Dart format
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo
      
      - name: Install Stable Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"
        
      - name: Format files
        run: dart format --set-exit-if-changed .
  
  dependency-validator:
    name: Validate dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
    
      - name: Install dependencies
        run: flutter pub get

      - name: Validate dependencies
        run: flutter pub run dependency_validator
    

