name: Build & Deploy to Web Preview

on:
  pull_request_target:
    branches: ["main"]

env:
  flutter_version: "3.10.0"

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    timeout-minutes: 10 # build should not take more than 10 minutes
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4 # Checkout the code in the main repo

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.3.2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"

      - name: Restore packages
        run: flutter pub get

      - name: Build Flutter
        run: flutter build web --release --web-renderer canvaskit

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: ksrv-njord
